#!/usr/bin/env bash
set -e

CURRENT_DIR=$(
  cd "$(dirname "$0")"
  pwd
)

if [ ! -d "$HOME"/.config ]; then
  mkdir "${HOME}"/.config
fi

ln -vfsn "${CURRENT_DIR}/nvim" "${HOME}"/.config/nvim
ln -vfsn "${CURRENT_DIR}/coc" "${HOME}"/.config/coc

if [ -f /.dockerenv ]; then
  sudo apt-get update
  export DEBIAN_FRONTEND=noninteractive

  # Neovim
  sudo apt install -y software-properties-common
  sudo add-apt-repository -y ppa:neovim-ppa/unstable
  sudo apt update
  sudo apt install -y neovim

  # ripgrep
  sudo apt install -y ripgrep

  # cleanup
  sudo rm -rf /var/lib/apt/lists/*
  sudo rm -rf /tmp/*
fi
